import type { Metadata } from "next";
import { Inter, Roboto, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import "./modern.css";
import "./utils.scss";

const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "100", "900"],
  variable: "--robo",
});

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "100", "900", "100", "200", "600", "800", "900"],
  variable: "--robo-cond",
});

export const metadata: Metadata = {
  title: "Quizzler",
  // description: "Generated by create next app",
};

const fonts = `${roboto.variable} ${robotoCondensed.variable}`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fonts}>{children}</body>
    </html>
  );
}
